/* ─────────────────────────────────────────────────────────────────
   Shared menu data for PopularToday + DigitalMenuPage
   ───────────────────────────────────────────────────────────────── */

export const POPULAR_ITEMS = [
  {
    id: 1,
    name: 'Signature Grilled Burger',
    description: 'Juicy 180g beef patty, caramelised onions, aged cheddar, house pickles and our secret green sauce on a brioche bun.',
    shortDesc: 'Juicy beef patty with caramelised onions and secret green sauce.',
    price: 14.99,
    rating: 4.9,
    orders: 320,
    badge: 'Best Seller',
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/alex-munsell-Yr4n8O_3UPc-unsplash_peadau.jpg',
    category: 'Burgers',
  },
  {
    id: 2,
    name: 'Truffle Margherita Pizza',
    description: 'Stone-baked 12″ base, San Marzano tomato sauce, fresh buffalo mozzarella, fresh basil, and a drizzle of black truffle oil.',
    shortDesc: 'Stone-baked with buffalo mozzarella and black truffle oil.',
    price: 18.50,
    rating: 4.8,
    orders: 275,
    badge: 'Popular',
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005070/eiliv-aceron-ZuIDLSz3XLg-unsplash_ip33xb.jpg',
    category: 'Pizza',
  },
  {
    id: 3,
    name: 'Creamy Pasta Carbonara',
    description: 'Al dente spaghetti tossed in a velvety sauce of free-range eggs, Pecorino Romano, guanciale, and cracked black pepper.',
    shortDesc: 'Velvety egg sauce with guanciale and Pecorino Romano.',
    price: 16.00,
    rating: 4.7,
    orders: 198,
    badge: null,
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005072/chad-montano-eeqbbemH9-c-unsplash_rcchek.jpg',
    category: 'Pasta',
  },
  {
    id: 4,
    name: 'Asian Noodle Bowl',
    description: 'Wok-tossed rice noodles, crispy tofu, pak choi, spring onions, sesame, soy-ginger broth. Vegan & gluten-free option available.',
    shortDesc: 'Wok-tossed noodles in aromatic soy-ginger broth.',
    price: 13.75,
    rating: 4.8,
    orders: 241,
    badge: 'Popular',
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005067/no-revisions-gA81ZTsql68-unsplash_xl32sr.jpg',
    category: 'Noodles',
  },
  {
    id: 5,
    name: 'Grilled Salmon Plate',
    description: 'Atlantic salmon fillet, lemon-herb butter, seasonal greens, baby potatoes and a dill cream sauce.',
    shortDesc: 'Atlantic salmon with lemon-herb butter and dill cream.',
    price: 22.00,
    rating: 4.9,
    orders: 189,
    badge: "Chef's Pick",
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/ian-dooley-TLD6iCOlyb0-unsplash_ylegsx.jpg',
    category: 'Seafood',
  },
  {
    id: 6,
    name: 'Smash-Stack Tacos',
    description: 'Three crispy corn tortillas loaded with smashed beef, jalapeño slaw, pickled red onion, avocado crema and cotija.',
    shortDesc: 'Crispy corn tortillas with smashed beef and avocado crema.',
    price: 15.25,
    rating: 4.7,
    orders: 162,
    badge: null,
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005065/chad-montano-MqT0asuoIcU-unsplash_cbl5ek.jpg',
    category: 'Tacos',
  },
  {
    id: 7,
    name: 'Garden Fresh Salad',
    description: 'Mixed heritage leaves, heirloom tomatoes, cucumber ribbons, toasted seeds, lemon vinaigrette and house-made croutons.',
    shortDesc: 'Heritage leaves with heirloom tomatoes and lemon vinaigrette.',
    price: 11.50,
    rating: 4.6,
    orders: 134,
    badge: null,
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005064/jo-sonn-M-tzZD5z720-unsplash_zqcyub.jpg',
    category: 'Salads',
  },
  {
    id: 8,
    name: 'Classic Fried Chicken',
    description: 'Double-fried buttermilk chicken, spicy honey glaze, pickled cucumber, served with golden waffle fries and garlic aioli.',
    shortDesc: 'Double-fried buttermilk chicken with spicy honey glaze.',
    price: 17.00,
    rating: 4.8,
    orders: 305,
    badge: 'Best Seller',
    image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005065/markus-winkler-WHtVB-RiW2I-unsplash_cg5gtt.jpg',
    category: 'Chicken',
  },
];

/* ─── Full menu categories ───────────────────────────────────────── */
export const MENU_CATEGORIES = [
  {
    id: 'starters',
    title: 'Starters',
    description: 'Light bites and shareable plates to kick off your meal.',
    items: [
      {
        id: 101,
        name: 'Crispy Calamari',
        description: 'Tender squid rings lightly fried in seasoned breadcrumbs, served with a zesty lemon aioli and fresh parsley.',
        shortDesc: 'Golden fried squid rings with zesty lemon aioli.',
        price: 9.50,
        rating: 4.6,
        orders: 210,
        badge: 'Popular',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/anh-nguyen-kcA-c3f_3FE-unsplash_sonrms.jpg',
        category: 'Starters',
      },
      {
        id: 102,
        name: 'Bruschetta Trio',
        description: 'Three slices of toasted sourdough topped with heirloom tomatoes, buffalo ricotta, and roasted garlic mushrooms.',
        shortDesc: 'Toasted sourdough with three gourmet toppings.',
        price: 8.25,
        rating: 4.5,
        orders: 178,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/alex-munsell-Yr4n8O_3UPc-unsplash_peadau.jpg',
        category: 'Starters',
      },
      {
        id: 103,
        name: 'Soup of the Day',
        description: 'Chef\'s freshly made seasonal soup served with a warm crusty roll and herb butter.',
        shortDesc: 'Freshly made seasonal soup with crusty roll.',
        price: 7.00,
        rating: 4.4,
        orders: 145,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005070/eiliv-aceron-ZuIDLSz3XLg-unsplash_ip33xb.jpg',
        category: 'Starters',
      },
      {
        id: 104,
        name: 'Garlic Bread Platter',
        description: 'Warm ciabatta slices brushed with roasted garlic butter and fresh herbs, with a side of marinara dip.',
        shortDesc: 'Warm ciabatta with roasted garlic butter and marinara.',
        price: 6.50,
        rating: 4.7,
        orders: 390,
        badge: 'Best Seller',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005072/chad-montano-eeqbbemH9-c-unsplash_rcchek.jpg',
        category: 'Starters',
      },
    ],
  },
  {
    id: 'mains',
    title: 'Main Course',
    description: 'Hearty and satisfying dishes crafted with quality ingredients.',
    items: [
      {
        id: 3,
        name: 'Creamy Pasta Carbonara',
        description: 'Al dente spaghetti tossed in a velvety sauce of free-range eggs, Pecorino Romano, guanciale, and cracked black pepper.',
        shortDesc: 'Velvety egg sauce with guanciale and Pecorino Romano.',
        price: 16.00,
        rating: 4.7,
        orders: 198,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005067/no-revisions-gA81ZTsql68-unsplash_xl32sr.jpg',
        category: 'Pasta',
      },
      {
        id: 5,
        name: 'Grilled Salmon Plate',
        description: 'Atlantic salmon fillet, lemon-herb butter, seasonal greens, baby potatoes and a dill cream sauce.',
        shortDesc: 'Atlantic salmon with lemon-herb butter and dill cream.',
        price: 22.00,
        rating: 4.9,
        orders: 189,
        badge: "Chef's Pick",
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/ian-dooley-TLD6iCOlyb0-unsplash_ylegsx.jpg',
        category: 'Seafood',
      },
      {
        id: 201,
        name: 'Slow-Braised Lamb Shank',
        description: 'Tender lamb shank slow-braised in red wine jus with rosemary, served with creamy mashed potato and roasted root vegetables.',
        shortDesc: 'Red wine braised lamb with mash and roasted veg.',
        price: 26.00,
        rating: 4.9,
        orders: 156,
        badge: "Chef's Pick",
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005065/chad-montano-MqT0asuoIcU-unsplash_cbl5ek.jpg',
        category: 'Mains',
      },
      {
        id: 4,
        name: 'Asian Noodle Bowl',
        description: 'Wok-tossed rice noodles, crispy tofu, pak choi, spring onions, sesame, soy-ginger broth. Vegan & gluten-free option available.',
        shortDesc: 'Wok-tossed noodles in aromatic soy-ginger broth.',
        price: 13.75,
        rating: 4.8,
        orders: 241,
        badge: 'Popular',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005064/jo-sonn-M-tzZD5z720-unsplash_zqcyub.jpg',
        category: 'Noodles',
      },
    ],
  },
  {
    id: 'pizza',
    title: 'Pizza',
    description: 'Stone-baked, hand-stretched pizzas with premium toppings.',
    items: [
      {
        id: 2,
        name: 'Truffle Margherita Pizza',
        description: 'Stone-baked 12″ base, San Marzano tomato sauce, fresh buffalo mozzarella, fresh basil, and a drizzle of black truffle oil.',
        shortDesc: 'Stone-baked with buffalo mozzarella and black truffle oil.',
        price: 18.50,
        rating: 4.8,
        orders: 275,
        badge: 'Popular',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005065/markus-winkler-WHtVB-RiW2I-unsplash_cg5gtt.jpg',
        category: 'Pizza',
      },
      {
        id: 301,
        name: 'BBQ Chicken Pizza',
        description: 'Smoky BBQ base, pulled chicken thigh, red onion, mozzarella, coriander and a drizzle of hot honey.',
        shortDesc: 'Smoky BBQ base with pulled chicken and hot honey.',
        price: 19.00,
        rating: 4.7,
        orders: 231,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/anh-nguyen-kcA-c3f_3FE-unsplash_sonrms.jpg',
        category: 'Pizza',
      },
      {
        id: 302,
        name: 'Roasted Veggie Pizza',
        description: 'Roasted courgette, peppers, aubergine, sundried tomatoes, feta, pesto base and rocket.',
        shortDesc: 'Roasted vegetables with feta, pesto and rocket.',
        price: 16.50,
        rating: 4.6,
        orders: 142,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/alex-munsell-Yr4n8O_3UPc-unsplash_peadau.jpg',
        category: 'Pizza',
      },
      {
        id: 303,
        name: 'Pepperoni & Jalapeño',
        description: 'Classic tomato base loaded with double pepperoni, fresh jalapeños, mozzarella and a spicy arrabbiata drizzle.',
        shortDesc: 'Double pepperoni, jalapeños and spicy arrabbiata drizzle.',
        price: 18.00,
        rating: 4.8,
        orders: 298,
        badge: 'Best Seller',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005070/eiliv-aceron-ZuIDLSz3XLg-unsplash_ip33xb.jpg',
        category: 'Pizza',
      },
    ],
  },
  {
    id: 'burgers',
    title: 'Burgers',
    description: 'Handcrafted burgers stacked high with the freshest ingredients.',
    items: [
      {
        id: 1,
        name: 'Signature Grilled Burger',
        description: 'Juicy 180g beef patty, caramelised onions, aged cheddar, house pickles and our secret green sauce on a brioche bun.',
        shortDesc: 'Juicy beef patty with caramelised onions and secret green sauce.',
        price: 14.99,
        rating: 4.9,
        orders: 320,
        badge: 'Best Seller',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005072/chad-montano-eeqbbemH9-c-unsplash_rcchek.jpg',
        category: 'Burgers',
      },
      {
        id: 8,
        name: 'Classic Fried Chicken',
        description: 'Double-fried buttermilk chicken, spicy honey glaze, pickled cucumber, served with golden waffle fries and garlic aioli.',
        shortDesc: 'Double-fried buttermilk chicken with spicy honey glaze.',
        price: 17.00,
        rating: 4.8,
        orders: 305,
        badge: 'Best Seller',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005067/no-revisions-gA81ZTsql68-unsplash_xl32sr.jpg',
        category: 'Chicken',
      },
      {
        id: 6,
        name: 'Smash-Stack Tacos',
        description: 'Three crispy corn tortillas loaded with smashed beef, jalapeño slaw, pickled red onion, avocado crema and cotija.',
        shortDesc: 'Crispy corn tortillas with smashed beef and avocado crema.',
        price: 15.25,
        rating: 4.7,
        orders: 162,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/ian-dooley-TLD6iCOlyb0-unsplash_ylegsx.jpg',
        category: 'Tacos',
      },
      {
        id: 401,
        name: 'Mushroom Swiss Melt',
        description: '180g beef patty, sautéed garlic mushrooms, melted Swiss cheese, caramelised shallots on a toasted potato bun.',
        shortDesc: 'Beef patty with garlic mushrooms and Swiss cheese melt.',
        price: 15.50,
        rating: 4.7,
        orders: 188,
        badge: 'Popular',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005065/chad-montano-MqT0asuoIcU-unsplash_cbl5ek.jpg',
        category: 'Burgers',
      },
    ],
  },
  {
    id: 'desserts',
    title: 'Desserts',
    description: 'Sweet endings crafted to delight every palate.',
    items: [
      {
        id: 501,
        name: 'Warm Chocolate Fondant',
        description: 'Rich dark chocolate fondant with a molten centre, served with vanilla bean ice cream and raspberry coulis.',
        shortDesc: 'Molten dark chocolate fondant with vanilla ice cream.',
        price: 8.50,
        rating: 4.9,
        orders: 267,
        badge: 'Best Seller',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005064/jo-sonn-M-tzZD5z720-unsplash_zqcyub.jpg',
        category: 'Desserts',
      },
      {
        id: 502,
        name: 'New York Cheesecake',
        description: 'Classic baked cheesecake on a buttery biscuit base, served with seasonal berry compote.',
        shortDesc: 'Baked cheesecake with seasonal berry compote.',
        price: 7.50,
        rating: 4.8,
        orders: 201,
        badge: 'Popular',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005065/markus-winkler-WHtVB-RiW2I-unsplash_cg5gtt.jpg',
        category: 'Desserts',
      },
      {
        id: 503,
        name: 'Mango Sorbet',
        description: 'House-made Alphonso mango sorbet scoops, coconut tuile, mint and passion fruit syrup. Vegan & dairy-free.',
        shortDesc: 'House-made mango sorbet with passion fruit syrup.',
        price: 6.00,
        rating: 4.6,
        orders: 143,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/anh-nguyen-kcA-c3f_3FE-unsplash_sonrms.jpg',
        category: 'Desserts',
      },
      {
        id: 504,
        name: 'Tiramisu',
        description: 'Layers of espresso-soaked ladyfinger biscuits, mascarpone cream and dusted with premium cocoa powder.',
        shortDesc: 'Espresso-soaked ladyfingers with mascarpone cream.',
        price: 7.75,
        rating: 4.7,
        orders: 175,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/alex-munsell-Yr4n8O_3UPc-unsplash_peadau.jpg',
        category: 'Desserts',
      },
    ],
  },
  {
    id: 'beverages',
    title: 'Juices & Beverages',
    description: 'Freshly pressed juices, smoothies and handcrafted drinks.',
    items: [
      {
        id: 601,
        name: 'Green Detox Juice',
        description: 'Cold-pressed spinach, cucumber, green apple, ginger and lemon. Packed with antioxidants and vitamins.',
        shortDesc: 'Cold-pressed spinach, apple, ginger and lemon.',
        price: 5.50,
        rating: 4.7,
        orders: 312,
        badge: 'Popular',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005070/eiliv-aceron-ZuIDLSz3XLg-unsplash_ip33xb.jpg',
        category: 'Juices',
      },
      {
        id: 602,
        name: 'Mango Lassi',
        description: 'Chilled Alphonso mango blended with creamy yoghurt, cardamom and a pinch of rose water. Refreshingly sweet.',
        shortDesc: 'Mango blended with yoghurt, cardamom and rose water.',
        price: 5.00,
        rating: 4.8,
        orders: 280,
        badge: 'Best Seller',
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005072/chad-montano-eeqbbemH9-c-unsplash_rcchek.jpg',
        category: 'Beverages',
      },
      {
        id: 603,
        name: 'Fresh Lemonade',
        description: 'Hand-squeezed lemon juice, mint, a touch of cane sugar and sparkling water. Served over crushed ice.',
        shortDesc: 'Hand-squeezed lemon, mint and sparkling water.',
        price: 4.50,
        rating: 4.6,
        orders: 225,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005067/no-revisions-gA81ZTsql68-unsplash_xl32sr.jpg',
        category: 'Beverages',
      },
      {
        id: 604,
        name: 'Berry Smoothie',
        description: 'Blended strawberries, blueberries, raspberries, banana, almond milk and a spoon of natural honey.',
        shortDesc: 'Mixed berries, banana and almond milk smoothie.',
        price: 6.00,
        rating: 4.8,
        orders: 194,
        badge: null,
        image: 'https://res.cloudinary.com/dltp00ewe/image/upload/v1772005066/ian-dooley-TLD6iCOlyb0-unsplash_ylegsx.jpg',
        category: 'Beverages',
      },
    ],
  },
];
